name: 'Repo Lockdown'

on:
  issues:
    types: opened
  pull_request_target:
    types: opened
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/repo-lockdown@v4
        with:
          process-only: 'prs'
          lock-pr: true
          skip-closed-pr-comment: true
